debug: updated pipeline for DAST test [skip ci]

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -167,6 +167,13 @@ jobs:
     #      echo "Application did not start in time"
      #     exit 1
 
+      - name: List container and ports
+        run: docker ps -a
+
+      - name: Test endpoint via curl
+        run: |
+          curl -v http://localhost:8080/actuator/health || echo "fails on curl"
+
       - name: Show Docker logs
         run: docker compose logs
 
