Update snyk-security.yml

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -27,8 +27,8 @@ jobs:
           distribution: 'temurin'
           java-version: '17' # change to 11 if your project uses Java 11
 
-      - name: Build project with Maven
-        run: mvn clean install -DskipTests
+    #  - name: Build project with Maven
+     #   run: mvn clean install -DskipTests
 
       - name: Set up Snyk CLI
         uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
@@ -36,7 +36,7 @@ jobs:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
       - name: Snyk Code test (SAST)
-        run: snyk code test --sarif --path=src/main/java > snyk-code.sarif || echo "Snyk Code failed"
+        run: snyk code test --sarif > snyk-code.sarif || echo "Snyk Code scan failed"
         continue-on-error: false
 
       - name: Upload SARIF to GitHub Code Scanning
